name = "nicosampler"
version = "0.0.1"
description = "weth example by bootnode"

[deploy.weth]
artifact = "WETH"

[contract.WETH]
artifact = "WETH"

[invoke.deposit]
target = ["WETH"]
func = "deposit"
value = "10000000000000000"
