name = "testing-safe"
version = "0.0.1"

[var.salt]
defaultValue = "0x0000000000000000000000000000000000000000000000000000000000000001"
description = "Salt used to calculate safe contract address"

[var.owners]
defaultValue = "0x9cf2288d8FA37051970AeBa88E8b4Fb5960c2385"
description = "Safe owners, comma separated"

[clone.mySafeImpl]
source = "safe-impl:1.4.1@main"
target = "safe-impl:1.4.1@main"
var.salt = "<%= settings.salt %>"

[clone.mySafe]
depends = ["clone.mySafeImpl"]
source = "safe:1.4.1@main"
var.salt = "<%= settings.salt %>"
var.owners = "<%= settings.owners %>"
