name = "nicosampler"
version = "0.0.2"
preset = "refactor"
description = "weth example"
deployers = ["0x8B15121E7a61c621520bF169D37759d8a0276246"]

[deploy.weth]
artifact = "WETH"

[invoke.deposit]
target = ["weth"]
func = "deposit"
value = "1000000000000000"
