name = "nicosampler-weth"
version = "0.1"
description = "weth example by bootnode"

[deploy.weth]
artifact = "WETH"

[invoke.deposit]
target = ["WETH"]
function = "deposit"
value = "10000000000000000"
