name = "nicosampler"
version = "0.0.1"
preset = "owned-greeter"
description = "Simple greeter project that can be owned"
keywords = ["sample", "greeter", "owned"]
deployers = ["0x88E9fa18C121512A894f64C105b2638F38Ff9194", "0xdfbAa994219c6CC7e30a57d26Be5dfAc359c9fB9"]preset = "clone"

[clone.greeter]
source = "owned-greeter:latest@main"
target = "owned-greeter:0.0.0@clone-clone"
options.salt = "owned-greeter-clone"

[invoke.setGreeting]
from = "0x7f28058F0b989430C7397782F797e300CDc10042"
target = ["greeter.Greeter"]
func = "setGreeting"
args = ["example greet 2"]
